language: python

python:
  - 3.7

git:
  depth: 1

script:
  - pip install --upgrade pip==20.1
  - make init
  - make tests
  - make lint
  - |
    # upgrade doc, but only when pushing to "dev" branch
    if [[ "$TRAVIS_BRANCH" == "dev" ]] && [[ "$TRAVIS_PULL_REQUEST" == false ]]; then
    ./publish-doc.sh
    fi